# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bueda}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christopher Peplin"]
  s.date = %q{2010-04-14}
  s.description = %q{Provides a lightweight Ruby wrapper for the Bueda API.}
  s.email = %q{peplin@bueda.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/bueda.rb",
     "lib/bueda/client.rb",
     "spec/bueda/client_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://bueda.com}
  s.post_install_message = %q{Make sure to register for an API key at http://bueda.com}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Provides a lightweight Ruby wrapper for the Bueda API.}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/bueda/client_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, ["= 0.5.2"])
      s.add_development_dependency(%q<rspec>, ["= 1.3"])
    else
      s.add_dependency(%q<httparty>, ["= 0.5.2"])
      s.add_dependency(%q<rspec>, ["= 1.3"])
    end
  else
    s.add_dependency(%q<httparty>, ["= 0.5.2"])
    s.add_dependency(%q<rspec>, ["= 1.3"])
  end
end

